version: '3.9'

services:
  web:
    build: .
    container_name: cnl_web
    restart: always
    volumes:
      - .:/app
      - ./instance:/app/instance
    expose:
      - "8000"
    environment:
      - FLASK_ENV=production
    networks:
      - cnl_network

  nginx:
    image: nginx:latest
    container_name: cnl_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
    depends_on:
      - web
    networks:
      - cnl_network

networks:
  cnl_network:
    driver: bridge
